# --- CONFIGURAÇÃO DO BANCO DE DADOS H2 ---
spring.datasource.url=jdbc:h2:mem:stoptopdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- CONFIGURAÇÕES DO HIBERNATE/JPA ---
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- HABILITAR O CONSOLE DO H2 NO NAVEGADOR ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console